### PR TITLE
Api changes

### PR DESCRIPTION
**Pull request by JonahBalshai**
My proposed changes to the safetyNet API.
Changing the types of safetyNetItem from: `situationControl, relaxation, pet, other`
to: `friends, sport, pet, other, music, personality`

### CODE REVIEW

**Comment by JonahBalshai** [comment]
> Just as a comment, please use meaningful commit messages, so that the other students can easily get what the changes are about. Thanks!
Sorry! Will look out for that in the future. I changed the PR description to properly explain what I changed.

**Review by isaschm — APPROVED** [review]
Looks good to me 🌴

**Review by redstarmy — COMMENTED** [review]
Perhaps I missed out on some of the design discussions but although situationcontrol and relaxation are motivators they can still be part of the safetynet right?

**Comment by jgraeger** [comment]
> Perhaps I missed out on some of the design discussions but although situationcontrol and relaxation are motivators they can still be part of the safetynet right?

By the proposed change, only the items listed in the enumeration could be part of the safetynet (there is still the `other` option).

**Comment by JonahBalshai** [comment]
> I merged this with the new structure of the specification. @JonahBalshai @redstarmy I ended up inserting all mentioned options within the enum. If you agreed on reducing the number of possible items, feel free to remove unnecessary fields again.

Thanks a lot! I think maybe we'll merge two fields according to the discussion I had on mattermost. Should I create a new PR for that or can I just do it by myself?

**Comment by jgraeger** [comment]
> > I merged this with the new structure of the specification. @JonahBalshai @redstarmy I ended up inserting all mentioned options within the enum. If you agreed on reducing the number of possible items, feel free to remove unnecessary fields again.
> 
> Thanks a lot! I think maybe we'll merge two fields according to the discussion I had on mattermost. Should I create a new PR for that or can I just do it by myself?

Please create a PR, so all frontend teams can agree on you proposed merge (or any other changes). @kopfsachen-dev/backend really does not care about what is stored in the safety net :)

**Comment by JonahBalshai** [comment]
> > > I merged this with the new structure of the specification. @JonahBalshai @redstarmy I ended up inserting all mentioned options within the enum. If you agreed on reducing the number of possible items, feel free to remove unnecessary fields again.
> > 
> > Thanks a lot! I think maybe we'll merge two fields according to the discussion I had on mattermost. Should I create a new PR for that or can I just do it by myself?
> 
> Please create a PR, so all frontend teams can agree on you proposed merge (or any other changes). @kopfsachen-dev/backend really does not care about what is stored in the safety net :)

Will do :)

**Pull request merged**
